# Generated by Django 6.0 on 2026-01-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_delete_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='abuot',
            new_name='about',
        ),
    ]
